### ISSUE TITLE
试了好多次都是这个结果

### ISSUE THREAD

**Issue by ARCHERXTY** [zhenxun-org/zhenxun_bot-deploy#31]
02-27 02:34:09 [SUCCESS] nonebot | Running NoneBot...
02-27 02:34:09 [INFO] uvicorn | Started server process [22926]
02-27 02:34:09 [INFO] uvicorn | Waiting for application startup.
02-27 02:34:10 [INFO] services | Database loaded successfully!
02-27 02:34:10 [INFO] nonebot_plugin_apscheduler | Scheduler Started
02-27 02:34:11 [ERROR] uvicorn | Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 648, in startup
    await handler()
  File "/home/zhenxun_bot/utils/browser.py", line 21, in start_browser
    _browser = await _playwright.chromium.launch()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages/playwright/async_api/_generated.py", line 14007, in launch
    await self._impl_obj.launch(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages/playwright/_impl/_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Executable doesn't exist at /root/.cache/ms-playwright/chromium-1041/chrome-linux/chrome
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝

02-27 02:34:11 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by ARCHERXTY** [comment]
解决了，到/root/.cache/ms-playwright路径把chromium文件夹版本重命名成报错里提示的/root/.cache/ms-playwright/chromium-1041版本就能用了。
